# Machine Learning Toolbox

### Course Description
Time series are all around us, from server logs to high frequency financial data. Managing and manipulating ordered observations is central to all time series analysis. The xts and zoo packages provide a set of powerful tools to make this task fast and mistake free. In this course, you will learn everything from the basics of xts to advanced tips and tricks for working with time series data in R.


### Note how can Resizing plots in the R kernel for Jupyter notebooks
https://blog.revolutionanalytics.com/2015/09/resizing-plots-in-the-r-kernel-for-jupyter-notebooks.html

    library(repr)

    # Change plot size to 4 x 3
    options(repr.plot.width=4, repr.plot.height=3)
    
### Note2 Generate a table 
https://www.tablesgenerator.com/markdown_tables


### Note 3 - DataFrames

In [6]:
library(xts)

Warning message:
"package 'xts' was built under R version 3.5.3"Loading required package: zoo
Warning message:
"package 'zoo' was built under R version 3.5.3"
Attaching package: 'zoo'

The following objects are masked from 'package:base':

    as.Date, as.Date.numeric



## 1) Introduction to eXtensible Time Series, using xts and zoo for time series
`xts` and `zoo` are just two of the many different types of objects that exist in R. This chapter will introduce the basic objects in xts and zoo and their components, and offers examples of how to construct and examine the data.

### 1.1) (video) Introducing xts and zoo objects
`xts` stands for "eXtensible Time Series" at the heart of `xts` is a `zoo` object, a matrix object plus a vector of times corresponding to each row, which in turn represents an observation in time to ilustrate it, we´ll crate a simple matrix called `x` and to track these observation we have dates in an object called `idx` Note that this index **must** be a true time object (`Date`,`POSIX times`,`timeDate`,`chron`,... etc) and this point we don´t have a times series, we´ll need to join these to create out xts object, to do this we call the `xts` constructor it has other arguments like:

    - tzone : to set times zones and 
    - unique : which will force all times be unique
  
the last thing you can use `coredata` is how you get the raw matrix back, and `index` is how you extract the data or times.

In [10]:
#XTS = Index +Matrix 
x<-matrix(1:4, nrow = 2, ncol = 2)
idx<-as.Date(c("2015-01-01","2015-02-01"))
x
idx

X<-xts(x, order.by = idx)
X
str(X)

#Deconstrunctiong xts
coredata(X, fmt = FALSE)
index(X)

[,1] [,2]
[1,] 1    3   
[2,] 2    4

[1] "2015-01-01" "2015-02-01"

           [,1] [,2]
2015-01-01    1    3
2015-02-01    2    4

An 'xts' object on 2015-01-01/2015-02-01 containing:
  Data: int [1:2, 1:2] 1 2 3 4
  Indexed by objects of class: [Date] TZ: UTC
  xts Attributes:  
 NULL


[,1] [,2]
[1,] 1    3   
[2,] 2    4

[1] "2015-01-01" "2015-02-01"

#### 1.1.1)  What is an xts object?
There are many different types of objects in R. With a variety of different features, each has a unique purpose. Some classes inherit behavior from their parents, allowing for custom extensions to existing and well-understood R objects. This makes it easy to adapt existing code to new functionality.

It is for this reason that `xts` extends the popular `zoo` class. Knowing this, and what you have seen so far, which of these statements is true?

- `xts` objects are matrix objects internally.
- `xts` objects are indexed by a formal time object.
- Most `zoo` methods work for xts

#### 1.1.2) More than a matrix
It is best to think of `xts` objects as normal R matrices, but with special powers. These powers let you manipulate your data as a function of time, as your data is now self-aware of when it exists in time. Before we can start to exploit these powers, it will be helpful to see how `xts` objects relate to their base-R relatives.

In this exercise, you will get a feel for `xts` and how it behaves like a matrix object. The xts object `ex_matrix` and matrix object `core` have been pre-loaded for you.

**Exercise**

- Load the xts package using the library() function.
- Look at the structure of the sample xts called ex_matrix using str().
- Given that ex_matrix is a matrix, extract the 3rd row and 2nd column.
- Now take the matrix core and extract the 3rd row and 2nd column. Notice the difference.

*Answer*

In [19]:
core<-matrix(c(1,2), nrow =3, ncol = 2, byrow = TRUE)
ex_matrix<-xts(core, order.by = as.Date(c("2016-06-01","2016-06-02","2016-06-03")))


# Load xts
library(xts)

# View the structure of ex_matrix
str(ex_matrix)

# Extract the 3rd observation of the 2nd column of ex_matrix
ex_matrix[3, 2]

# Extract the 3rd observation of the 2nd column of core 
core[3, 2]

An 'xts' object on 2016-06-01/2016-06-03 containing:
  Data: num [1:3, 1:2] 1 1 1 2 2 2
  Indexed by objects of class: [Date] TZ: UTC
  xts Attributes:  
 NULL


           [,1]
2016-06-03    2

[1] 2

#### 1.1.3) Your first xts object
`xts` objects are simple. Think of them as a matrix of observations combined with an index of corresponding dates and times.
    
      xts = matrix + times
      
The main `xts` constructor takes a number of arguments, but the two most important are `x` for the **data** and `order.by` for the **index**. `x` must be a vector or matrix. `order.by` is a vector which must be the same length or number of rows as x, be a proper time or date object (very important!), and be in increasing order.

`xts` also allows you to bind arbitrary key-value attributes to your data. This lets you keep metadata about your object inside your object. To add these at creation, you simply pass additional `name = value` arguments to the xts() function.

Since we are focusing here on the mechanics, we'll use random numbers as our data so we can focus on creating the object rather than worry about its contents.

**Exercise**
- Create an object called data that contains five random numbers using rnorm().
- Create a Date class index from "2016-01-01" of length five called dates.
- Use the xts constructor to create an object called smith using data and dates as the index.
- Create an object called bday which contains a POSIXct date object containing the date "1899-05-08".
- Create an xts object called hayek using data, dates, and a new attribute called born, which should contain the birthday object you just created.

*Answer*

In [21]:
# Create the object data using 5 random numbers
data<-rnorm(5)

# Create dates as a Date class object starting from 2016-01-01
dates <- seq(as.Date("2016-01-01"), length = 5, by = "days")

# Use xts() to create smith
smith <- xts(x = data, order.by = dates)

# Create bday (1899-05-08) using a POSIXct date class object
bday <- as.POSIXct("1899-05-08")

# Create hayek and add a new attribute called born
hayek <- xts(x = data, order.by = dates, born = bday)

#### 1.1.4) Deconstructing xts
Now that you can create `xts` objects, your next task is to examine an xts object from the inside.

At the core of both `xts` and `zoo` is a simple R matrix with a few additional attributes. The most important of these attributes is the `index`. The `index` holds all the information we need for `xts` to treat our data as a time series.

When working with time series, it will sometimes be necessary to separate your time series into its core data and index attributes for additional analysis and manipulation. The core data is the matrix portion of xts. You can separate this from the xts object using `coredata()`. The index portion of the xts object is available using the `index()` function. Note that both of these functions are methods from the zoo class, which `xts` extends.

In this exercise you will use these built-in functions to extract both the internal matrix data and internal index from your sample `xts` object. You will use the `hayek` time series you created in the last exercise to practice these new functions.

**Exercise**

- Extract the core data of hayek using coredata() and call this hayek_core.
- View the class of hayek_core using the class() function.
- Extract the date index of hayek using index() and call this hayek_index.
- View the class of hayek_index.

*Answer*

In [22]:
# Extract the core data of hayek
hayek_core<-coredata(hayek)

# View the class of hayek_core
class(hayek_core)

# Extract the index of hayek
hayek_index<-index(hayek)

# View the class of hayek_index
class(hayek_index)

[1] "matrix"

[1] "Date"

#### 1.1.5) Time based indices
`xts` objects get their power from the index attribute that holds the time dimension. One major difference between `xts` and most other time series objects in R is the ability to use any one of various classes that are used to represent time. Whether `POSIXct`, `Date`, or some other class, xts will convert this into an internal form to make subsetting as natural to the user as possible.

    a <- xts(x = 1:2, as.Date("2012-01-01") + 0:1)
    a[index(a)]

We'll get into more detail on subsetting `xts` objects in a later chapter. For now you can simply use date objects to index appropriate rows from your time series. You can think of this as effectively matching the rownames you see in the object. This works as anticipated for time objects because the rownames are really dates!

For this exercise you'll create two time series using two different time classes. You will then subset each object using the other object's index.

In [ ]:
library(repr)
# Change plot size to 4 x 3
    options(repr.plot.width=4, repr.plot.height=3)

In [ ]:
**Exercise**

*Answer*